### 회원가입

POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "name": "임훈묵",
  "age": "33",
  "loginId": "limhunmuk@gmail.com",
  "password": "1234"
}


### 로그인
# @no-redirect
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "loginId": "admin",
  "password": "1234"
}

### 사용자 페이지

GET http://localhost:8080/user

"Authorization: Bearer {eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMTM5OTkxNCwiZXhwIjoxNzMxNDg2MzE0fQ.8khLuBGHoULeOrse--_rsaKQvKMs8pv7b6NaKtzeRVJyBWE5sZBruKgbo53vmd4tciLp5Eug1uEeHFU4M91Tcw}"


### 관리자 페이지

GET http://localhost:8080/admin

"Authorization: Bearer {eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMTM5OTkxNCwiZXhwIjoxNzMxNDg2MzE0fQ.8khLuBGHoULeOrse--_rsaKQvKMs8pv7b6NaKtzeRVJyBWE5sZBruKgbo53vmd4tciLp5Eug1uEeHFU4M91Tcw}"


### 메인 페이지

GET http://localhost:8080/api/post