### 게시글 작성

POST http://localhost:8080/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNjMwMDE3OSwiZXhwIjoxNzM2Mzg2NTc5fQ.fp7esFHdOHXI_qg4b0JPVaZwJuUJvwLdBFb6ei91WEnL7YOjvUlqMSho749KvbkPvNEl26vxgV7yU-2YYpxiXg

{
  "title": "제목입니다.",
  "content": "내용입니다."
}

### 게시글 조회

GET http://localhost:8080/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNjMwMDE3OSwiZXhwIjoxNzM2Mzg2NTc5fQ.fp7esFHdOHXI_qg4b0JPVaZwJuUJvwLdBFb6ei91WEnL7YOjvUlqMSho749KvbkPvNEl26vxgV7yU-2YYpxiXg



### 게시글 조회

GET http://localhost:8080/api/post/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNjMwMDE3OSwiZXhwIjoxNzM2Mzg2NTc5fQ.fp7esFHdOHXI_qg4b0JPVaZwJuUJvwLdBFb6ei91WEnL7YOjvUlqMSho749KvbkPvNEl26vxgV7yU-2YYpxiXg


### 게시글 삭제

DELETE http://localhost:8080/posts/3
Content-Type: application/json
